client_config_backend: settings
client_config:
  client_id: 150038502150-4nis3a6eba07rp2ufd8r4ck5f4ld4sk3.apps.googleusercontent.com
  client_secret: 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
  
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file